### ISSUE TITLE
加油，我正好需要一个这样的组件

### ISSUE THREAD

**Issue by sulmz** [Preyou/split-box#1]
我是从知乎看到的

**Comment by sulmz** [comment]
有几个问题希望得到您的解答：
1、是否支持一行3列的形式？
2、示例中的import { UseElementSize } from '@vueuse/components'，这是从哪来的？

**Comment by Preyou** [comment]
> 有几个问题希望得到您的解答： 1、是否支持一行3列的形式？ 2、示例中的import { UseElementSize } from '@vueuse/components'，这是从哪来的？

1. 支持任意嵌套，对容器内部的行列数没有限制
2. 这个在注释中应该有提到，这是使用的第三方库，vueuse。这是一个在vue中有着极高使用率的库，堪称vue界的loash，你也可以考虑用其他库来获取宽高。目前，我并没有提供原生获取宽高的方法，因为我想把他打造成一个只用css控制的库，后面也许会考虑通过style或者css变量的方式将宽高原生暴露出来。

最后感谢你的支持，我也是第一次尝试开源，大家的意见或者建议我都会仔细考虑的。

**Comment by Preyou** [comment]
> 有几个问题希望得到您的解答： 1、是否支持一行3列的形式？ 2、示例中的import { UseElementSize } from '@vueuse/components'，这是从哪来的？

1. 支持任意嵌套，对容器内部的行列数没有限制
2. 这个在注释中应该有提到，这是使用的第三方库，vueuse。这是一个在vue中有着极高使用率的库，堪称vue界的loash，你也可以考虑用其他库来获取宽高。目前，我并没有提供原生获取宽高的方法，因为我想把他打造成一个只用css控制的库，后面也许会考虑通过style或者css变量的方式将宽高原生暴露出来。

最后感谢你的支持，我也是第一次尝试开源，大家的意见或者建议我都会仔细考虑的。
